services:
  prefect:
    image: prefecthq/prefect:3-latest
    container_name: prefect-server
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: ${PREFECT_API_DATABASE_CONNECTION_URL}
      PREFECT_API_URL: ${PREFECT_API_URL}
    ports:
      - "4200:4200"
    command: >
      bash -c "apt-get update && apt-get install -y curl && prefect server start --host 0.0.0.0 --port 4200 & echo 'Waiting for Prefect server...'; until curl -s http://localhost:4200/api/health | grep -q '\"database\":\"healthy\"'; do sleep 2; done; echo 'Server healthy!'; prefect work-pool ls | grep -q etl-workers || prefect work-pool create etl-workers --type process;"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:4200/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5


  prefect-worker:
    build:
      context: .
      dockerfile: ./worker_base_img/Dockerfile
    container_name: prefect-worker
    environment:
      PREFECT_API_URL: ${PREFECT_API_URL}
      DB_URL: ${DB_URL}
    depends_on:
      prefect:
        condition: service_healthy