"""Create company table

Revision ID: 991440c34f0b
Revises: 
Create Date: 2025-09-30 23:30:33.037720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '991440c34f0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('isin_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('isin_code'),
    sa.UniqueConstraint('symbol')
    )
    op.create_index(op.f('ix_companies_isin_code'), 'companies', ['isin_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_isin_code'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
