http:
  routers:

    whoami:
      rule: Host(`whoami.market-mitra.online`)
      entryPoints:
        - websecure
      middlewares:
        - authelia
        - enterprise-security
      service: whoami
      tls:
        certResolver: letsencrypt

    dashboard:
      rule: Host(`dashboard.market-mitra.online`)
      entryPoints:
        - websecure
      middlewares:
        - authelia
        - content-blocker
        - enterprise-security
      service: dashbaord
      tls:
        certResolver: letsencrypt

    # Authelia has been by passed to access the service by another machine with fixed api key
    prefect-api:
      rule: Host(`prefect-api.market-mitra.online`) && PathPrefix(`/api`)
      entryPoints:
        - websecure
      service: prefect
      middlewares: 
        - api-key-auth
        - enterprise-security
      tls:
        certResolver: letsencrypt

    prefect:
      rule: Host(`prefect.market-mitra.online`)
      entryPoints:
        - websecure
      middlewares:
        - authelia
        - content-blocker
        - enterprise-security
      service: prefect
      tls:
        certResolver: letsencrypt

    authelia:
      rule: Host(`auth.market-mitra.online`)
      entryPoints:
        - websecure
      service: authelia
      middlewares:
        - enterprise-security
      tls:
        certResolver: letsencrypt

    lldap:
      rule: Host(`dap.market-mitra.online`)
      entryPoints:
        - websecure
      service: lldap
      middlewares:
        - authelia
        - enterprise-security
      tls:
        certResolver: letsencrypt

  services:
    whoami:
      loadBalancer:
        servers:
          - url: http://whoami:80

    prefect:
      loadBalancer:
        servers:
          - url: http://prefect:4200

    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091

    lldap:
      loadBalancer:
        servers:
          - url: http://lldap:17170

    dashbaord:
      loadBalancer:
        servers:
          - url: http://next-dashboard:3000